export interface SongGenre {
  genre: string;
  songs: string[];
}

export const songList: SongGenre[] = [
  {
    genre: "Rock / Classic Rock",
    songs: [
      "Won't Back Down - Tom Petty",
      "Feelin' Alright - Joe Cocker",
      "Call Me Al - Paul Simon",
      "Drops of Jupiter - Train",
      "Hard To Handle - Black Crows",
      "Mr. Brightside - The Killers",
      "Mr. Jones - Counting Crows",
      "Stuck in the Middle - Steeler's Wheel",
      "American Girl - Tom Petty",
      "Semi Charmed Life - Third Eye Blind",
      "This Love - Maroon 5",
      "Hotel California - The Eagles",
      "What's Up - Four Non Blondes",
      "Sweet Home Alabama - Lynyrd Skynyrd",
      "Piano Man - Billy Joel",
      "Hey Jude - The Beatles",
      "Brown Eyed Girl - Van Morrison",
      "Cripple Creek - The Band",
      "Don't Stop Believing - Journey",
      "3AM - Matchbox 20",
      "Mary Jane's Last Dance - Tom Petty",
      "Hold My Hand - Hootie and the Blowfish",
      "Jessie's Girl - Rick Springfield",
      "Bohemian Rhapsody - Queen",
      "Fat Bottomed Girls - Queen",
      "Dreams - Fleetwood Mac",
      "Can't You See - Marshall Tucker Band",
      "Higher - Creed",
      "Everlong - Foo Fighters",
      "S.O.B. - Nathaniel Rateliff & the Night Sweats",
    ],
  },
  {
    genre: "Pop / Top 40",
    songs: [
      "Anti-Hero - Taylor Swift",
      "Blank Space - Taylor Swift",
      "Redbone - Childish Gambino",
      "Sunday Morning - Maroon 5",
      "Queen Of California - John Mayer",
      "Under the Bridge - Red Hot Chili Peppers",
      "Shape of You - Ed Sheeran",
      "Slow Hands - Niall Horan",
      "Valerie - Amy Winehouse",
      "Lovely Day - Bill Withers",
      "Don't Wanna Live Forever - Zayn and Taylor Swift",
      "You Make My Dreams - Hall & Oates",
      "Feel It Still - Portugal. The Man",
      "There's Nothing Holding Me Back - Shawn Mendes",
      "Ride - Twenty One Pilots",
      "The Middle - Zedd",
      "I Try - Macy Gray",
      "That's What I Like - Bruno Mars",
      "Stitches - Shawn Mendes",
      "Truth Hurts - Lizzo",
      "Talk - Khalid",
      "All I Want For Christmas Is You - Mariah Carey",
      "Good As Hell - Lizzo",
      "Blinding Lights - The Weeknd",
      "Not Over You - Gavin DeGraw",
      "Peaches - Justin Bieber",
      "Love Yourself - Justin Bieber",
    ],
  },
  {
    genre: "Soul / R&B / Funk",
    songs: [
      "Kissing My Love - Bill Withers",
      "Pony - Ginuwine",
      "I Wish - Stevie Wonder",
      "PYT - Michael Jackson",
      "Kiss - Prince",
      "Superstition - Stevie Wonder",
      "Signed Sealed Delivered - Stevie Wonder",
      "Tell Me Something Good - Chaka Khan/Rufus",
      "Boogie On Reggae Woman - Stevie Wonder",
      "I Wanna Be Your Lover - Prince",
      "Purple Rain - Prince",
      "If I Ain't Got You - Alicia Keys",
    ],
  },
  {
    genre: "Country",
    songs: [
      "Chicken Fried - Zac Brown Band",
      "Meant to Be - Florida Georgia Line",
      "Drink in My Hand - Eric Church",
      "Friends in Low Places - Garth Brooks",
      "Tennessee Whiskey - Chris Stapleton",
      "Beer Never Broke My Heart - Luke Combs",
      "When It Rains It Pours - Luke Combs",
      "Whitehouse Road - Tyler Childers",
      "You Should Probably Leave - Chris Stapleton",
      "Save a Horse - Big & Rich",
      "Wagon Wheel - Old Crow Medicine Show/Darius Rucker",
      "Pour Me A Drink - Post Malone/Blake Shelton",
      "I Had Some Help - Morgan Wallen/Post Malone",
      "Whiskey Glasses - Morgan Wallen",
      "Headin South - Zach Bryan",
      "Revival - Zach Bryan",
    ],
  },
  {
    genre: "Indie / Alternative",
    songs: [
      "Not The Only One - Sam Smith",
      "Time To Pretend - MGMT",
      "Perfect - Ed Sheeran",
      "Shut Up and Dance - Walk the Moon",
      "Whatever It Takes - Imagine Dragons",
      "Sex on Fire - Kings of Leon",
      "Back Down South - Kings of Leon",
      "Gold on the Ceiling - Black Keys",
      "Ain't No Rest for the Wicked - Cage the Elephant",
      "Dial Drunk - Noah Kahan",
      "My Body - Young the Giant",
      "Midnight City - M83",
      "Fix You - Coldplay",
      "Yellow - Coldplay",
      "When You Were Young - The Killers",
      "Northern Attitude - Noah Kahan/Hozier",
      "Pink Pony Club - Chappell Roan",
    ],
  },
  {
    genre: "Hip-Hop / Rap",
    songs: [
      "Hey Ya! - Outkast",
      "Tipsy (A Bar Song) - Shaboozey",
    ],
  },
  {
    genre: "Reggae / Ska",
    songs: [
      "Caress Me Down - Sublime",
      "Badfish - Sublime",
      "Three Little Birds - Bob Marley",
    ],
  },
  {
    genre: "Folk / Acoustic",
    songs: [
      "Neon - John Mayer",
      "Stop This Train - John Mayer",
      "Why Georgia - John Mayer",
      "Slow Dancing in a Burning Room - John Mayer",
      "Waiting on the World to Change - John Mayer",
      "Little Lion Man - Avett Brothers",
      "Ho Hey - The Lumineers",
    ],
  },
  {
    genre: "Punk / Emo / Pop Punk",
    songs: [
      "My Own Worst Enemy - Lit",
      "The Middle - Jimmy Eat World",
      "All the Small Things - Blink-182",
      "What's My Age Again - Blink-182",
      "Sugar, We're Going Down - Fall Out Boy",
      "Teenage Dirtbag - Wheatus",
      "Ain't It Fun - Paramore",
    ],
  },
  {
    genre: "Classic Pop / Oldies",
    songs: [
      "Stand by Me - Ben E. King",
      "The Joker - Steve Miller Band",
      "Africa - Toto",
      "Sweet Caroline - Neil Diamond",
      "Dance With Somebody - Whitney Houston",
      "I Want It That Way - Backstreet Boys",
      "Your Song - Elton John",
      "Bennie and the Jets - Elton John",
      "Tiny Dancer - Elton John",
      "Rocket Man - Elton John",
    ],
  },
  {
    genre: "Christian / Southern Rock",
    songs: [
      "The Outsiders - NEEDTOBREATHE",
      "Washed by the Water - NEEDTOBREATHE",
      "White Horse - Chris Stapleton",
    ],
  },
];
